MISSION_CONTROL_HTML = r"""<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CleaningAI OS · Mission Control</title>
<style>
:root{color-scheme:dark;--bg:#07111f;--panel:#102036;--line:#243b55;--text:#e8f0f7;--muted:#8da4b8;--accent:#2dd4bf;--warn:#f59e0b}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#12345a 0,var(--bg) 38%);font:15px system-ui;color:var(--text)}header{padding:26px 5vw 15px;display:flex;justify-content:space-between;align-items:center}h1{font-size:24px;margin:0}button,input{font:inherit}.key{background:#091726;border:1px solid var(--line);border-radius:8px;padding:8px;color:var(--text)}main{padding:10px 5vw 50px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card{background:rgba(16,32,54,.9);border:1px solid var(--line);border-radius:14px;padding:16px}.metric{font-size:30px;font-weight:700;color:var(--accent)}.muted{color:var(--muted)}h2{font-size:17px;margin:28px 0 10px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--line)}th{color:var(--muted)}.status{padding:3px 8px;border-radius:99px;background:#17334a}.warning{color:var(--warn)}nav button{background:transparent;border:0;color:var(--muted);padding:8px;cursor:pointer}nav button:hover{color:var(--accent)}#error{color:#fca5a5;margin:10px 0;white-space:pre-wrap}@media(max-width:650px){header{display:block}.key{width:100%;margin-top:12px}.wide{overflow:auto}}
</style></head><body>
<header><div><h1>CleaningAI OS</h1><div class="muted">Mission Control · единый контур управления компанией</div></div><input id="key" class="key" type="password" placeholder="API key (production)"></header>
<main><div id="error"></div><section id="metrics" class="grid"></section><h2>Модули</h2><section id="modules" class="grid"></section><h2>Задачи агентов</h2><div class="card wide"><table><thead><tr><th>ID</th><th>Агент</th><th>Задача</th><th>Статус</th><th>Попытки</th></tr></thead><tbody id="tasks"></tbody></table></div><h2>Решения владельца</h2><div class="card wide"><table><thead><tr><th>ID</th><th>Действие</th><th>Ресурс</th><th>Статус</th></tr></thead><tbody id="approvals"></tbody></table></div></main>
<script>
const key=document.querySelector('#key');key.value=sessionStorage.cleaningApiKey||'';key.onchange=()=>{sessionStorage.cleaningApiKey=key.value;load()};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(path){const headers={'X-Role':'owner','X-Actor':'mission-control'};if(key.value)headers['X-API-Key']=key.value;const r=await fetch(path,{headers});if(!r.ok)throw new Error(path+': '+r.status+' '+await r.text());return r.json()}
function card(label,value,sub=''){return `<div class="card"><div class="muted">${esc(label)}</div><div class="metric">${esc(value)}</div><div class="muted">${esc(sub)}</div></div>`}
async function load(){try{document.querySelector('#error').textContent='';const[d,t,a]=await Promise.all([get('/api/dashboard'),get('/api/tasks'),get('/api/approvals')]);document.querySelector('#metrics').innerHTML=card('Здоровье компании',d.company_health+'%')+card('Открытые задачи',d.open_tasks)+card('Ожидают владельца',d.pending_approvals)+card('Ошибки',d.failed_tasks);const m=d.modules;document.querySelector('#modules').innerHTML=card('Продажи',m.sales.pipeline_amount+' ₽',m.sales.total+' лидов · '+m.sales.won+' побед')+card('Тендеры',m.tenders.active,m.tenders.overdue+' просрочено')+card('HR',m.hr.available,m.hr.candidates+' кандидатов доступны')+card('Финансы',m.finance.net_amount+' ₽',m.finance.overdue_payments+' платежей просрочено')+card('Маркетинг',m.marketing.active,m.marketing.campaigns+' кампаний');document.querySelector('#tasks').innerHTML=t.slice(0,30).map(x=>`<tr><td>#${x.id}</td><td>${esc(x.agent_type)}</td><td>${esc(x.title)}</td><td><span class="status">${esc(x.status)}</span></td><td>${x.attempts}/${x.max_attempts}</td></tr>`).join('')||'<tr><td colspan=5 class=muted>Задач нет</td></tr>';document.querySelector('#approvals').innerHTML=a.slice(0,30).map(x=>`<tr><td>#${x.id}</td><td>${esc(x.action_kind)}</td><td>${esc(x.resource_type)} #${esc(x.resource_id)}</td><td><span class="status">${esc(x.status)}</span></td></tr>`).join('')||'<tr><td colspan=4 class=muted>Запросов нет</td></tr>'}catch(e){document.querySelector('#error').textContent=e.message}}
load();setInterval(load,15000);
</script></body></html>"""
